check function for dependencies

diff --git a/pnglatex b/pnglatex
--- a/pnglatex
+++ b/pnglatex
@@ -37,6 +37,16 @@ SIZE=
 TEXFILE=
 declare -r VERSION=0.13
 
+# Check for dependencies
+#  montanaflynn/check_for_dependencies.sh
+
+checkfor () {
+    command -v $1 >/dev/null 2>&1 || { 
+        echo >&2 "$1 required by pnglatex"; 
+        exit 1; 
+    }
+}
+
 # Add margin, border and padding to the image.
 function box {
     if [ "$PADDING" ]; then
@@ -171,11 +181,15 @@ function generate {
 
 # Entry point of the script.
 function main {
-    if ! exists latex || ! exists dvipng; then
-        echo "pnglatex requires latex and dvipng packages." >&2
-        exit 1
-    fi
-
+   # if ! exists latex || ! exists dvipng; then
+     #   echo "pnglatex requires latex and dvipng packages." >&2
+      #  exit 1
+   # fi
+    checkfor "dvipng"
+    checkfor "imagemagick"
+    checkfor "latex"
+    checkfor "optipng"
+    
     properties
     parse "$@"
 
